version: "3.8"

services:
  # Development environment container
  dev_env:
    build:
      context: ./dev_env
    container_name: dev_env_lisp
    # Mount your local user’s ~/.gitconfig as read-only,
    # plus the entire project directory for code editing.
    volumes:
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
      - ./:/workspace
    working_dir: /workspace
    # Run as the same user/group as your host to avoid permission issues
    user: "${UID}:${GID}"
    tty: true

  # Hunchentoot app container
  hunchentoot_app:
    build:
      context: ./hunchentoot_app
    container_name: hunchentoot_app
    ports:
      - "8084:8084"
